[tool.poetry]
name = "gardena-bluetooth"
version = "0.1.0"
description = ""
authors = ["Joakim Plate <elupus@ecce.se>"]
readme = "README.md"
packages = [{include = "gardena_bluetooth"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
